server:
  port: 8089
spring:
  application:
    name: wecahtsdk_demo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.222.222.77:3306/demo
      username: root
      password: MXMPbrxyc4t9sBje

  redis:
    host: 124.222.222.77
    port: 6379
    password: MXMPbrxyc44tsaeredis
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
wecahtsdk:
  #  群机器人名字，建议跟自己微信昵称保持一致，方便@直接使1用
  name: 咸王
#  写入自己的gpt的sk
  OPENAI_API_KEY: sk-DsMFscY6ZUztjj394WEdT9BlbkFJochgQPqRRP0SfQWg1zA4
#  这个不必更改，反向代理直接调用gpt接口
  OPENAI_API_URL: https://ls.zhao9wan6.work/proxy/api.openai.com/v1/chat/completions
#微信对话平台token
  token: tX0WlgYSJwGpv5vHf6N4iZHNfFq5g4

#  mysql中就使用了这一张表，其他用的都是redis
#  CREATE TABLE `wx_voice` (
#  `id` int(11) NOT NULL AUTO_INCREMENT,
#  `from_wx` varchar(255) DEFAULT NULL,
#  `to_wx` varchar(255) DEFAULT NULL,
#  `address` varchar(255) DEFAULT NULL,
#  `times` varchar(255) DEFAULT NULL,
#  `liao` varchar(255) DEFAULT NULL,
#  PRIMARY KEY (`id`)
#  ) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4
