server:
  port: 8089
spring:
  application:
    name: wecahtsdk_demo
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      本地数据库
      #      url: jdbc:mysql://localhost:3306/reggie
      #      云服务数据库
      url: jdbc:mysql://124.222.221.77:3306/reggie
      username: root
      #      password: root
      password: MXMPbrxyc4t7sBje

  redis:
    #    redis本地主机ip
    #    host: 127.0.0.1
    #    redis云服务ip
    host: 124.222.221.77
    #    port: 6379
    #    为了防止入侵，不用原端口号6379，生产用6378，密码也进行修改
    port: 6378
    #    password:
    password: MXMPbrxyc4t7sBjeredis
    database: 0
#  cache:
#    redis:
#      time-to-live: 1800000 #设置缓存数据的过期时间不写的话默认永久生效
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
wecahtsdk:
  #  群机器人名字，建议跟自己微信昵称保持一致，方便@直接使用
  name: 咸王
